package models

import "github.com/jinzhu/gorm"

// ListDB is used to interact with the list database
//
// For pretty much all single gallery queries:
// If the gallery is found, we will return a nil error
// If the gallery is not found, we will return ErrNotFound
// If there is another error, we will return an error with
// more information about what went wrong. This may not be
// an error generated by the models package.
type ListDB interface {
	ByID(id uint) (*List, error)
	ByUserID(id uint) ([]List, error)
	Create(list *List) error
	Update(list *List) error
	Delete(id uint) error
}

type List struct {
	gorm.Model
	UserID uint   `gorm:"not_null;index"`
	Title  string `gorm:"not_null"`
}
